export const CLOUDINARY = 'Cloudinary';

export const AVATARDEFAULT = "https://img.freepik.com/free-psd/3d-illustration-person-with-sunglasses_23-2149436188.jpg?size=338&ext=jpg&ga=GA1.1.1700460183.1712620800&semt=sph"


export enum InjectionToken {
    // WALLET_REPOSITORY = 'WALLET_REPOSITORY',
    // ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY',
    // USER_REPOSITORY = 'USER_REPOSITORY',
    // HISTORY_REPOSITORY = 'HISTORY_REPOSITORY',
    // TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY',
    // AUTHENTICATOR = 'AUTHENTICATOR',
    // CONTRACT_SERVICE = 'CONTRACT_SERVICE',
    LANGUAGE_REPOSITORY = "LANGUAGE_REPOSITORY",
    ROLEMEMBERPROJECT_REPOSITORY = "ROLEMEMBERPROJECT_REPOSITORY",
    LANGUAGEMEMBER_REPOSITORY= "LANGUAGEMEMBER_REPOSITORY",
    TECHNICALMEMBER_REPOSITORY = "TECHNICALMEMBER_REPOSITORY",
    DOCXTEMPLATE_REPOSITORY = "DOCXTEMPLATE_REPOSITORY",
    POSITIONMEMBER_REPOSITORY = "POSITIONMEMBER_REPOSITORY",
    PROJECTHISTORY_REPOSITORY = "PROJECTHISTORY_REPOSITORY"

}